binop_separator = "Back"
# brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 100
# control_brace_style = "AlwaysNextLine"
edition = "2018"
error_on_line_overflow = true
# error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 120
merge_derives = false
imports_granularity = "Crate"
imports_layout = "Vertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
# Wait for stabilization
reorder_impl_items = true
group_imports = "StdExternalCrate"
